apiVersion: v1
kind: Secret
metadata:
  name: readarr-apikey
type: Opaque
stringData:
  apikey: ENC[AES256_GCM,data:30OKFrUkXjd50tITnIJ+0dI3YQevAV31qRrUJY6qM8E=,iv:sR86FJ3W9HuUKRD3Llk8OymZdB+6ZCEtv+g1Efoe2Ls=,tag:KyT6F6r6lNFeaZ4mNkbRfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMjUvT0phbTdLdzZOelY0
        N3JGT1JnZW9MS2tSWHpwWm5aOEVWNy9saTJFCkt3aFBBTjRuOStpb2hSM2pVMnJp
        RERqeHYzMjBLQlJONHFBTFNQdGZZMXcKLS0tIFkwTkdkQm1CcjUxVjEzWkZkSHg3
        TXVYSnJxVUducnFOMjZZVlBWVjZ5NnMKK3UGzthi9DuPUSf1C4HJU55YuPXtE/lr
        YQxG4ys3rs5tpdypwiCiaSdk9k5hwwuJjVKKamq6NM/jTZ8zW5+1PQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-19T00:04:27Z"
  mac: ENC[AES256_GCM,data:EvZ3OoMDmsTHi/1LRz95vtYP9/qbDA/kIOC0rvQgweMImvUe1MBacg8BdZnWfLb2AboE6nDg3B9eneDKKNffqodMjWHtCfiXYa0e2GxXMLNvargv2sEzIsc5U285Snp4K/xda7pL55M5wFWuqT/CE414pmqxdNipaf6xhHo4YUI=,iv:0nnRWvpqnMs5kdX+FmdRyQa394D3hg7HiiwV1WxXuVg=,tag:GnITI1VwpvEY3s1rqQq98w==,type:str]
  mac_only_encrypted: true
  version: 3.9.3
