---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Keeper
  category: Calendars
  description: Keeper is an open-source calendar sync tool and optional MCP server (https://github.com/ridafkih/keeper.sh)
  url: https://${APP}.${ROOT_DOMAIN}
  access_policy:
    groups:
      - friends
      - family
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/
      method: GET
      conditions:
        - "[STATUS] == 200"
