---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        DATABASE_URL: "{{ .postgres_uri }}"
        REDIS_URL: "redis://valkey.database.svc.cluster.local:6379"
        BETTER_AUTH_SECRET: "{{ .keeper_password }}"
        ENCRYPTION_KEY: "{{ .keeper_password }}"
        # TRUSTED_ORIGINS: "${TRUSTED_ORIGINS}"
  dataFrom:
    - extract:
        key: 'Keeper Secret Key'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "keeper_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
