---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpgate-config
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: warpgate-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      templateFrom:
        - target: Data
          configMap:
            name: warpgate-config
            items:
              - key: warpgate.yaml
                templateAs: Values
  dataFrom:
    - extract:
        key: '${APP}-oidc-credentials'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: network
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpgate-api-token
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: warpgate-api-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: 'Warpgate API Token'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
