---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  namespace: equestria
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        MEILI_NO_ANALYTICS: "true"
        MEILI_MASTER_KEY: "{{ .meili_password }}"
  dataFrom:
    - extract:
        key: 'MeiliSearch Secret Key'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "meili_$1"
