---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: warpgate-operator
spec:
  interval: 1h
  url: oci://ghcr.io/thereisnotime/charts/warpgate-operator
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "0.x"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: warpgate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: warpgate-operator
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    strategy:
      name: RetryOnFailure
  uninstall:
    keepHistory: false
  values:
    webhooks:
      certManager:
        enabled: true
        issuerRef:
          name: ""
