---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app warpgate-operator
  namespace: &namespace equestria
  labels:
    app.kubernetes.io/name: *app
    driscoll.dev/name: *app
spec:
  targetNamespace: warpgate-operator-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      driscoll.dev/name: *app
  dependsOn:
    - name: cert-issuers
      namespace: cert-manager
  path: ./kubernetes/apps/equestria/home/warpgate-operator
  prune: true
  wait: true
  force: false
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
