---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-values
  namespace: equestria
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-values
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      templateFrom:
      - target: Data
        configMap:
          name: ${APP}-values
          items:
            - key: values.yaml
              templateAs: Values
  dataFrom:
    - extract:
        key: 'Neo4J Password'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "neo4j_$1"

