---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: neo4j
spec:
  interval: 1h
  url: https://helm.neo4j.com/neo4j
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neo4j
spec:
  chart:
    spec:
      chart: neo4j
      version: 2026.2.3
      sourceRef:
        kind: HelmRepository
        name: neo4j
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: Secret
      name: ${APP}-values
      valuesKey: values.yaml
