apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-apikey
type: Opaque
stringData:
  apikey: ENC[AES256_GCM,data:Ilns/oNlAQU0d+zvhwoL9WrDFqf97OOv6XL8pSfr0ViHg5yQddHvOwZTDtVNyz3vcWbed9YBcSnGRi6liEyFUzk6P7tPRe/kcT2YkCE10+OzoIIlraekbJa6dbMjCd/Hy0dhT91xAp6ObGVQMqm1qmWvhAhK2di+G9axsNXye86EtdzHSN2Yq1A7VKbV0w9HLvui6iQz1jei79i3aSYlqeWg6jLXs8NPQwJjcwCUFKxAYiSe8au/aW/rnCePKxTc245Y,iv:Gc7A5GW2cWjS9s0A8hS6pTiURhoDcSycUZrpdTrJGH0=,tag:G88B8vjgtI+sVYRiaETMIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR3JoZXpmWU8yZVdmQnRp
        NElUeU1wMFpOdGVWNUEzdUxVWTJyTmNsQ3pFCk5VYmhQeWFZN003Tm91ZFlBNXla
        LzJNR1BZMXFseWtlb3lEb1d2SWkvRXcKLS0tIDZQRFFYWDNFMTllNWN0OXRMV2JC
        Zm9taVVCbE9NNXJTYUhnMGNSYThDcWcKiPqbNnPfBoQ8Df6pJOydbq2moEmv3pzc
        ahxpEUw0P1ClGdxKD/RLp3X5ddDfk+8AhHp8UfAsq1n/R9R2nTTCKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-19T00:04:17Z"
  mac: ENC[AES256_GCM,data:9PHVmsJWKpkziqpDut7rOwLHv2O2VplcpZzm+0FCJxVX9jx+bsC4hoE35K+RDk2N5AlDCWpfJKvZZr93OJNOD/Kjojinv5LNfycUcY/Ba9vdOyQDbJW5vhFXroDEjuQsFXEq0NmnFM5a36zJTxxFvKEg7yTTOHdhnihymHKwt6g=,iv:gf/UpJJurdsrUS74S3iuJGlImG5249xfdZZe+RQqwew=,tag:9uGc1rEEuXHa9rP6EBdH0w==,type:str]
  mac_only_encrypted: true
  version: 3.9.3
