#!/bin/bash
# docker run --rm -v .:/app/config/ glanceapp/glance config:print
op run --no-masking -- docker run -e ROOT_DOMAIN -e AUTHENTIK_API_TOKEN -e CF_ACCOUNTID -e CF_USERNAME -e CF_CREDENTIAL -e EQUESTRIA_TUNNEL_USERNAME -e EQUESTRIA_TUNNEL_CREDENTIAL -e SGC_TUNNEL_USERNAME -e SGC_TUNNEL_CREDENTIAL -e PROWLARR_APIKEY -e UNIFI_API_KEY -e GITHUB_TOKEN -e GRAFANA_TOKEN -e SONARR_API_KEY -e TAUTULLI_API_KEY -e SABNZBD_API_KEY -e JELLYFIN_API_KEY -e PLEX_API_KEY -e JELLYFIN_USER_ID -e IMMICH_API_KEY -p 8080:8080 --rm -v .:/app/config/ glanceapp/glance

