---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openbao
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.29.0
    digest: sha256:350329a1cdff86f8225d4d659cc79a737205d7ca527a219df7b3760d65629213
  url: oci://ghcr.io/openbao/charts/openbao
