---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        DATABASE_URL: "{{ .postgres_uri }}"
        REDIS_URL: "redis://valkey.database.svc.cluster.local:6379"
        ENCRYPTION_KEY: "{{ .outline_password }}"
        OIDC_ISSUER_URL: "{{ .oidc_issuer }}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_DISPLAY_NAME: "${CLUSTER_TITLE}"
  dataFrom:
    - extract:
        key: 'Outline Secret Key'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "outline_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: '${APP}-oidc-credentials'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: cluster
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
