---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pinepods
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 15m
  driftDetection:
    mode: enabled
  timeout: 15m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 911
            runAsGroup: 911
            supplementalGroups: [0, 1, 44, 109, 303, 911, 10000]
        containers:
          *app :
            image:
              repository: madeofpendletonwool/pinepods
              tag: 0.8.2
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: ${APP}-env
            env:
              TZ: "${TIMEZONE}"
              PUID: ${PUID}
              PGID: ${PGID}
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 2
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
                  initialDelaySeconds: 5
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        seccompProfile:
          type: RuntimeDefault
      shareProcessNamespace: true

    persistence:
      downloads:
        existingClaim: truenas-media
        globalMounts:
          - path: /downloads
            subPath: downloads/podcasts
      backups:
        existingClaim: ${APP}
        globalMounts:
          - path: /backups
            subPath: backups

    service:
      *app :
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &port 8040
      backend:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &port_backend 5000
      podpeople:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &port_podpeople 8085

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
