apiVersion: v1
kind: Secret
metadata:
  name: iptv-proxy-secret
type: Opaque
stringData:
  PROXY_USERNAME: ENC[AES256_GCM,data:XpsJlQ==,iv:VQZImsaj2vBolaETuOSCHM8RT9AHG3U9aWPqtZR2gTE=,tag:yG7sBHJbxAtpRf/AXIGk/w==,type:str]
  PROXY_PASSWORD: ENC[AES256_GCM,data:kueD8A==,iv:hvVdwyfIVu3Mjut1bNQPo8o2l0I/7KPC5uX5/dnbxbw=,tag:lBJC6iPK+gbv7ngMUa4RNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKclpCVkFtaTZMcWZYOVkx
        UDIrMXVCaU5KYVY2ZklBOFEwWE5HMjlLRFRJCldKclRWRWNFaXR6ajU0aE5GcnEx
        bHlKSEoyUzAxbjVzN3JsR3Y2b0tzZDAKLS0tIHpycTN3Mm5VanZDQXNlU25WUWk1
        VFpkZGhaNEY4Vjhpdzc1VFVlTG4rQWMKX3GWcRfK8x4Dq1IokeiqbLRsdxJP4EDg
        QqE7RMqar6rGgUsUrPSQBhvd34qQoRgEG0u7nKfQNQEHn88q9NqYMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-22T20:05:08Z"
  mac: ENC[AES256_GCM,data:FSQeDvS/swv2MphmeuNDKxrttckdVwDokKdaDlvZ03XcMdofrCwpB/RQR8d1SrWzhCTA2cdoRGpG61RX4GGNE/YdwJFBAGEfOGH4cyydVyNDK2jVdEV6mxHQiB2HmPSbr5gwp7IGXxPoEW8Bc7FyVWKePk/3XdA3wujGURz6C+Y=,iv:fLI7TNnOf40826fwxFqvxDtcBV/lV4XoE8jYXwdz9dk=,tag:VxqynajPqV+yAjeaL37QqQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
